import { Injectable } from '@nestjs/common';
import { ArticleQuery, ArticlesQuery, PagingInfoCommand } from '@universal-repo-nx/shared-models';
@Injectable()
export class AppService {
  data: ArticleQuery[] = [
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 2, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 3, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },
    { id: 4, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 1, title: "test", content: "aaaa" },
    { id: 21312312, title: "test", content: "aaaa" },

  ];

  getArticles(query: PagingInfoCommand): ArticlesQuery {
    const totalCount = this.data.length;
    const perPage = query.perPage;
    const pagesCount = Math.round(this.data.length / perPage);
    const currentPage = query.currentPage;
    const isLastPage = query.currentPage == pagesCount;


    const startingIndex = (currentPage - 1) * perPage;// 0 10 20 30
    const endingIndex = currentPage * perPage;// 10 20 30

    return new ArticlesQuery({
      data: this.data.slice(startingIndex, endingIndex),
      pagingInfo: {
        totalCount,
        perPage,
        isLastPage,
        pagesCount,
        currentPage,
      },
    })
  }
}
