# File for Pull Request on master branch
name: PR on aosa

# When a PR is opened to master
on:
  pull_request:
    branches:
      - aosa-main
    types: [opened, reopened, synchronize]

jobs:
  build:
    # Setup OS and Node Version
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Use Node.js '16'
        uses: actions/setup-node@v1
        with:
          node-version: 16
          # Make sure we have all branches
      - name: Fetch other branches
        run: git fetch --no-tags --prune --depth=5 origin master

      - name: Install environment
        run: npm i
        
      - name: build
        run: npm run nx build aosa

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run nx build aosa
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
